// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaeD4rOtTEHAJcLSgLwwffTZ969M4S16Q',
    appId: '1:998910794403:web:a5bf8a47a45c13a89d7d16',
    messagingSenderId: '998910794403',
    projectId: 'focal-plateau-448322-s2',
    authDomain: 'focal-plateau-448322-s2.firebaseapp.com',
    storageBucket: 'focal-plateau-448322-s2.firebasestorage.app',
    measurementId: 'G-G1RD1F4JTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz870Q8yQnq51Vho1C-RPU7yewJcyA4vo',
    appId: '1:998910794403:android:939b13f4b94fc65a9d7d16',
    messagingSenderId: '998910794403',
    projectId: 'focal-plateau-448322-s2',
    storageBucket: 'focal-plateau-448322-s2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzs_Ivm08PNsdHv5m0Yiab_VqWlJIMqIo',
    appId: '1:998910794403:ios:8a0102f512804f329d7d16',
    messagingSenderId: '998910794403',
    projectId: 'focal-plateau-448322-s2',
    storageBucket: 'focal-plateau-448322-s2.firebasestorage.app',
    iosBundleId: 'com.example.aseCapstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzs_Ivm08PNsdHv5m0Yiab_VqWlJIMqIo',
    appId: '1:998910794403:ios:8a0102f512804f329d7d16',
    messagingSenderId: '998910794403',
    projectId: 'focal-plateau-448322-s2',
    storageBucket: 'focal-plateau-448322-s2.firebasestorage.app',
    iosBundleId: 'com.example.aseCapstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaeD4rOtTEHAJcLSgLwwffTZ969M4S16Q',
    appId: '1:998910794403:web:b9547fcb4393497d9d7d16',
    messagingSenderId: '998910794403',
    projectId: 'focal-plateau-448322-s2',
    authDomain: 'focal-plateau-448322-s2.firebaseapp.com',
    storageBucket: 'focal-plateau-448322-s2.firebasestorage.app',
    measurementId: 'G-SMP3WF2NBS',
  );
}
